name: Publish Docker Image To Dockerhub

on:
  push:
   branches: [ 90ad5646ff0501cf354a93c18b686fc7c8ca7a13 ]
  pull_request:
    branches: [ 90ad5646ff0501cf354a93c18b686fc7c8ca7a13 ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "dibssbd" --password-stdin
        docker image build -t dibssbd/adux:v3 .
        docker push dibssbd/adux:v3
